apiVersion: v2
name: chaos
description: A Helm chart for harness chaos module

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "0.4.1"

dependencies:
  - name: chaos-common
    version: 0.3.x
    repository: "file://../chaos-common"

  - name: chaos-driver
    version: 0.4.x
    repository: "file://../chaos-driver"

  - name: chaos-manager
    version: 0.4.x
    repository: "file://../chaos-manager"

  - name: chaos-web
    version: 0.4.x
    repository: "file://../chaos-web"

  - name: chaos-k8s-ifs
    version: 0.3.x
    repository: "file://../chaos-k8s-ifs"

  - name: chaos-linux-ifs
    version: 0.2.x
    repository: "file://../chaos-linux-ifs"

  - name: chaos-linux-ifc
    version: 0.2.x
    repository: "file://../chaos-linux-ifc"

  - name: chaos-infra
    version: 0.1.x
    repository: "file://../chaos-infra"
