global:
  loadbalancerURL: "test@harness.io"
  airgap: false
  ha: false
  opa:
    enabled: false
  cd:
    # -- Enable to install CD
    enabled: true
  chaos:
    enabled: true
  # Enable if using ingress objects
  ingress:
    enabled: true
    loadBalancerIP: '34.23.21.25'
    className: "harness"
    loadBalancerEnabled: true
    hosts:
      - ''
    tls:
      enabled: false
      secretName: harness-ssl
    nginx:
      # -- Create Nginx Controller.  True will deploy a controller into your cluster
      create: true
    defaultbackend:
      # -- Create will deploy a default backend into your cluster
      create: true


## Platform Settings
platform:
  harness-manager:
    featureFlags:
      OPA: "OPA_PIPELINE_GOVERNANCE"
      ADDITIONAL: "CHAOS_ENABLED,FF_CHAOS_LINUX_ENABLED"

chaos-manager:
  replicaCount: 3
  maxSurge: 1
  maxUnavailable: 0

  waitForInitContainer:
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: IfNotPresent
      tag: "latest"
      digest: ""
      imagePullSecrets: []
      
  image:
    registry: docker.io
    repository: chaosnative/harness-smp-chaos-manager
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.9.6
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  jobs:
    chaos_db_upgrade:
      enabled: false
      slackURLToNotify: 'no-url'
      image:
        registry: docker.io
        tag: 0.9.0
        repository: chaosnative/harness-smp-chaos-db-upgrade-agent
        pullPolicy: Always
        digest: ""
        imagePullSecrets: []

  subscriberImage:
    image:
      registry: docker.io
      repository: chaosnative/harness-smp-chaos-subscriber
      tag: 0.9.0
      digest: ""

  argoWorkflowControllerImage:
    image:
      registry: docker.io
      repository: chaosnative/workflow-controller
      tag: v3.3.1
      digest: ""

  argoWorkflowExecutorImage:
    image:
      registry: docker.io
      repository: chaosnative/argoexec
      tag: v3.3.1
      digest: ""

  litmusChaosOperatorImage:
    image:
      registry: docker.io
      repository: chaosnative/chaos-operator
      tag: 3.0.0-stable
      digest: ""

  litmusChaosRunnerImage:
    image:
      registry: docker.io
      repository: chaosnative/chaos-runner
      tag: 3.0.0-stable
      digest: ""

  litmusChaosExporterImage:
    image:
      registry: docker.io
      repository: chaosnative/chaos-exporter
      tag: 3.0.0-stable
      digest: ""

  logWatcherImage:
    image:
      registry: docker.io
      repository: chaosnative/harness-chaos-log-watcher
      tag: release-chaos-log-watcher-0.8.0
      digest: ""

  enterpriseHubBranchName: 'hce-3.0.2-saas'

  chaosExperimentLimit: '1000'

  chaosHubLimit: '30'

  chaosGamedayLimit: '200'

  chaosHubSize: '200'

  parallelChaosExperimentRuns: '25'

  skipSecureVerify: 'true'

  configmap: {}

  mongoSecrets:
    userName:
      name: harness-secrets
      key: mongodbUsername
    password:
      name: mongodb-replicaset-chart
      key: mongodb-root-password

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "harness-default"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080
    targetport: 8080
    grpcport: 8081
    targetgrpcport: 8081

  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 600m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaos-web:
  replicaCount: 3
  maxSurge: 1
  maxUnavailable: 0

  image:
    registry: docker.io
    repository: chaosnative/harness-smp-chaos-web
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.9.6
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  enableCDN: 'false'

  configmap: {}

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "harness-default"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8184
    targetport: 8184

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaos-driver:
  replicaCount: 3
  maxSurge: 1
  maxUnavailable: 0

  waitForInitContainer:
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: IfNotPresent
      tag: "latest"
      digest: ""
      imagePullSecrets: []

  image:
    registry: docker.io
    repository: chaosnative/harness-smp-chaos-driver
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.9.0
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  configmap: {}

  mongoSecrets:
    userName:
      name: harness-secrets
      key: mongodbUsername
    password:
      name: mongodb-replicaset-chart
      key: mongodb-root-password

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "harness-default"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 9000
    targetport: 9000

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaos-linux-ifc:

  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 0

  waitForInitContainer:
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: IfNotPresent
      tag: "latest"
      digest: ""
      imagePullSecrets: []
      
  image:
    registry: docker.io
    #repository: chaosnative/harness-smp-chaos-delegate-controller
    repository: chaosnative/harness-smp-chaos-linux-infra-controller
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ci
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  configmap: {}

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "chaos-linux-ifc-sa"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaos-linux-ifs:

  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 0

  waitForInitContainer:
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: IfNotPresent
      tag: "latest"
      digest: ""
      imagePullSecrets: []
      
  image:
    registry: docker.io
    #repository: chaosnative/harness-smp-chaos-delegate-controller
    repository: chaosnative/harness-smp-chaos-linux-infra-server
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ci
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  configmap: {}

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "chaos-linux-ifs-sa"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaos-k8s-ifs:
  replicaCount: 3
  maxSurge: 1
  maxUnavailable: 0
  skipSecureVerify: "true"

  waitForInitContainer:
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: IfNotPresent
      tag: "latest"
      digest: ""
      imagePullSecrets: []

  image:
    registry: docker.io
    repository: chaosnative/harness-smp-chaos-k8s-ifs
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.9.2
    digest: ""
    #imagePullSecrets: ["chaos-regcred-secret"]

  configmap: {}

  mongoSecrets:
    userName:
      name: harness-secrets
      key: mongodbUsername
    password:
      name: mongodb-replicaset-chart
      key: mongodb-root-password

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "harness-default"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    #runAsUser: 65534
    #runAsNonRoot: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 6000
    targetport: 6000

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  autoscaling: {}
    #enabled: false
    #minReplicas: 1
    #maxReplicas: 2
    #targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
