apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-linux-ifs-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-driver.labels" . | nindent 4 }}
data:
  PROBE_SOURCE_IMAGE: {{ include "chaos-linux-ifs.probeSourceImage" . }}
