apiVersion: v1
kind: Service
metadata:
  name: chaos-linux-ifs-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "chaos-linux-ifs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: chaos-linux-gql-ifs
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetport}}

  selector:
    component: chaos-linux-ifs
   {{- include "chaos-linux-ifs.selectorLabels" . | nindent 4 }}
