apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-k8s-ifs-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "chaos-k8s-ifs.labels" . | nindent 4 }}
data:
  SKIP_SECURE_VERIFY: '{{ .Values.skipSecureVerify }}'
  PORTAL_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/chaos/kserver/api'
  INFRA_DEPLOYMENTS: "[\"app=chaos-exporter\", \"name=chaos-operator\", \"app=workflow-controller\"]"
  ARGO_WORKFLOW_CONTROLLER_IMAGE: {{ include "chaos-k8s-ifs.argoWorkflowControllerImage" . }}
  ARGO_WORKFLOW_EXECUTOR_IMAGE: {{ include "chaos-k8s-ifs.argoWorkflowExecutorImage" . }}
  LITMUS_CHAOS_OPERATOR_IMAGE: {{ include "chaos-k8s-ifs.litmusChaosOperatorImage" . }}
  LITMUS_CHAOS_RUNNER_IMAGE: {{ include "chaos-k8s-ifs.litmusChaosRunnerImage" . }}
  LITMUS_CHAOS_EXPORTER_IMAGE: {{ include "chaos-k8s-ifs.litmusChaosExporterImage" . }}
  SUBSCRIBER_IMAGE: {{ include "chaos-k8s-ifs.subscriberImage" . }}  
  CONTAINER_RUNTIME_EXECUTOR: 'k8sapi'
  K8S_IFS_VERSION: '1.15.0'
  K8S_INFRA_CONNECTION_TYPE: "https"
  DEFAULT_CHAOS_EXPERIMENT_LIMIT: '{{ .Values.chaosExperimentLimit }}'
  DEFAULT_CHAOS_HUB_LIMIT: '{{ .Values.chaosHubLimit }}'
  DEFAULT_CHAOS_GAMEDAY_LIMIT: '{{ .Values.chaosGamedayLimit }}'
  DEFAULT_CHAOS_HUB_SIZE: '{{ .Values.chaosHubSize }}'
  DEFAULT_PARALLEL_CHAOS_EXPERIMENT_RUNS: '{{ .Values.parallelChaosExperimentRuns }}'
  DEFAULT_CHAOS_EXPERIMENT_RUN_LIMIT: '100000'
  DEFAULT_GAME_DAY_RUNS_PER_GAME_DAY_LIMIT: '1000'
  DEFAULT_EXPERIMENTS_PER_GAME_DAY_RUN_LIMIT: '20'
  INFRA_HEALTH_CHECK_TIMEOUT: "900000"
