apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-k8s-ifs-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "chaos-k8s-ifs.labels" . | nindent 4 }}
data:
  SKIP_SECURE_VERIFY: '{{ .Values.skipSecureVerify }}'
