apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-k8s-ifs-config
  namespace: {{ .Release.Namespace | quote }}
data:
  CHAOS_MANAGER_ENDPOINT: 'http://chaos-manager-service.{{ .Release.Namespace }}.svc.cluster.local:8080'
  LOG_SERVICE_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
