apiVersion: v1
data:
  LOG_SERVICE_TOKEN: Yzc2ZTU2N2EtYjM0MS00MDRkLWE4ZGQtZDk3Mzg3MTRlYjgy
  CUSTOM_TLS_CERT: {{ .Values.customTlsCert }}
kind: Secret
metadata:
  name: chaos-k8s-ifs-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-k8s-ifs.labels" . | nindent 4 }}
type: Opaque
