# Default values for chaos-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: "test@harness.io"
  cd:
    # -- Enable to install CD
    enabled: true
  # Enable if using ingress objects
  ingress:
    enabled: true
    loadBalancerIP: '0.0.0.0'
    className: "harness"
    loadBalancerEnabled: true
    hosts:
      - ''
    tls:
      enabled: false
      secretName: harness-ssl
    nginx:
      # -- Create Nginx Controller.  True will deploy a controller into your cluster
      create: true
    defaultbackend:
      # -- Create will deploy a default backend into your cluster
      create: true

## Platform Settings
platform:
  harness-manager:
    featureFlags:
      OPA: "OPA_PIPELINE_GOVERNANCE"
      ADDITIONAL: "CHAOS_ENABLED"

replicaCount: 3
# TODO: remove this
deployAsSts: false
replicaCountSts: 0
maxSurge: 1
maxUnavailable: 0

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
    imagePullSecrets: []

image:
  registry: docker.io
  repository: chaosnative/harness-smp-chaos-manager
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.11.1"
  digest: ""
  #imagePullSecrets: ["chaos-regcred-secret"]

jobs:
  chaos_db_upgrade:
    enabled: false
    slackURLToNotify: 'no-url'
    image:
      registry: docker.io
      tag: "0.11.0"
      repository: chaosnative/harness-smp-chaos-db-upgrade-agent
      pullPolicy: Always
      digest: ""
      imagePullSecrets: []

#allowedOrigns: "[*.*.*.*]"

subscriberImage:
  image:
    registry: docker.io
    repository: chaosnative/harness-smp-chaos-subscriber
    tag: 0.11.0
    digest: ""

argoWorkflowControllerImage:
  image:
    registry: docker.io
    repository: chaosnative/workflow-controller
    tag: v3.3.1
    digest: ""

argoWorkflowExecutorImage:
  image:
    registry: docker.io
    repository: chaosnative/argoexec
    tag: v3.3.1
    digest: ""

litmusChaosOperatorImage:
  image:
    registry: docker.io
    repository: chaosnative/chaos-operator
    tag: 3.0.0-stable
    digest: ""

litmusChaosRunnerImage:
  image:
    registry: docker.io
    repository: chaosnative/chaos-runner
    tag: 3.0.0-stable
    digest: ""

litmusChaosExporterImage:
  image:
    registry: docker.io
    repository: chaosnative/chaos-exporter
    tag: 3.0.0-stable
    digest: ""

logWatcherImage:
  image:
    registry: docker.io
    repository: chaosnative/harness-chaos-log-watcher
    tag: release-chaos-log-watcher-0.11.0
    digest: ""

enterpriseHubBranchName: 'hce-3.0.3-smp'

chaosExperimentLimit: '1000'

chaosHubLimit: '30'

chaosGamedayLimit: '200'

chaosHubSize: '200'

parallelChaosExperimentRuns: '25'

skipSecureVerify: 'true'

configmap: {}

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  #runAsUser: 65534
  #runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetport: 8080
  grpcport: 8081
  targetgrpcport: 8081

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 600m
    memory: 512Mi

autoscaling: {}
  #enabled: false
  #minReplicas: 1
  #maxReplicas: 2
  #targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# extraVolumes:
#   - name: volume-test
#     configMap:
#       name: test-config
#       # readOnly: true
extraVolumes: []

# extraVolumeMounts:
#   - name: volume-test
#     mountPath: /opt/harness/config
extraVolumeMounts: []

lifecycleHooks: {}
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command: