apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chaos-driver-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-driver.labels" . | nindent 4 }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: chaos-driver
