apiVersion: v1
data:
  CHAOS_SERVICE_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  JWT_SECRET: ZE9rZHNWcWRSUFBSSkczMVhVMHFZNE1QcW1CQk1rMFBUQUdJS002TzdUR3Foanl4U2NJZEplODBtd2g1WWI1ekYzS3hZQkh3NkIzTGZ6bHE=
kind: Secret
metadata:
  name: chaos-driver-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-driver.labels" . | nindent 4 }}
type: Opaque
