apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-common-config
  namespace: {{ .Release.Namespace | quote }}
data:
  REDIS_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_SSL_ENABLED: 'true'
  REDIS_DATABASE: '0'
