apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-common-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-common.labels" . | nindent 4 }}
data:
  REDIS_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_SSL_ENABLED: 'false'
  REDIS_CERT_PATH: '/opt/harness/svc/redis_labs_ca_truststore'
  REDIS_DATABASE: '0'
  INFRA_COMPATIBLE_VERSIONS: '["0.8.0","0.9.0"]'
  CHAOS_MANAGER_GRPC_ENDPOINT: 'chaos-manager-service:8081'
  LOG_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/log-service'
  NG_MANAGER_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/ng/api'
  CHAOS_MANAGER_ENDPOINT: 'http://chaos-manager-service.{{ .Release.Namespace }}.svc.cluster.local:8080'
  ACCESS_CONTROL_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/authz/api'
