apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-common-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-common.labels" . | nindent 4 }}
data:
  REDIS_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_SSL_ENABLED: 'false'
  REDIS_CERT_PATH: '/opt/harness/svc/redis_labs_ca_truststore'
  REDIS_DATABASE: '0'
  INFRA_COMPATIBLE_VERSIONS: '["0.13.0","0.14.0","1.15.0"]'
  CHAOS_MANAGER_GRPC_ENDPOINT: 'chaos-manager-service:8081'
  LOG_SERVICE_ENDPOINT: 'http://log-service:8079'
  LOG_SERVICE_EXTERNAL_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/log-service'
  NG_MANAGER_ENDPOINT: 'http://ng-manager:7090'
  CHAOS_MANAGER_ENDPOINT: 'http://chaos-manager-service:8080'
  ACCESS_CONTROL_ENDPOINT: 'http://access-control:9006/api'
  REDIS_EVENTS_FWK_NAMESPACE: ''
  REDIS_LOCK_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_LOCK_SSL_ENABLED: 'false'
  REDIS_LOCK_NAMESPACE: ''
  REDIS_LOCK_DATABASE: '0'
  NG_MANAGER_SVC_ENDPOINT: 'http://ng-manager:7090'
  #REDIS_STREAM_ENV: 'smp'
