apiVersion: v1
data:
  CHAOS_SERVICE_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  REDIS_PASSWORD: ""
  SEGMENT_API_KEY: ""
kind: Secret
metadata:
  name: chaos-common-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-common.labels" . | nindent 4 }}
type: Opaque
