apiVersion: v1
data:
  CHAOS_SERVICE_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  REDIS_PASSWORD: ""
  JWT_SECRET: ZE9rZHNWcWRSUFBSSkczMVhVMHFZNE1QcW1CQk1rMFBUQUdJS002TzdUR3Foanl4U2NJZEplODBtd2g1WWI1ekYzS3hZQkh3NkIzTGZ6bHE=
  NG_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  JWT_IDENTITY_SERVICE_SECRET: SFZTS1VZcUQ0ZTVSeHUxMmhGRGRDSktHTTY0c3hnRXludmREaGFPSGFUSGh3d24wSzRUdHIwdW9PeFNzRVZZTnJVVT0=
  REDIS_PASSWORD: ""
  SEGMENT_API_KEY: ""
  LOG_SERVICE_TOKEN: "Yzc2ZTU2N2EtYjM0MS00MDRkLWE4ZGQtZDk3Mzg3MTRlYjgy"
  SLACK_URL: ""
kind: Secret
metadata:
  name: chaos-common-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-common.labels" . | nindent 4 }}
type: Opaque
