---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-linux-ifc
  namespace: '{{ .Release.Namespace }}'
  labels:
    name: chaos-linux-ifc
    {{- include "chaos-linux-ifc.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: ["delete","deletecollection"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["taskdefinitions","linuxchaosexperiments","chaosresults"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["linuxchaosexperiments/finalizers"]
    verbs: ["update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","create","list","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-linux-ifc
  namespace: '{{ .Release.Namespace }}'
  labels:
    name: chaos-linux-ifc
    {{- include "chaos-linux-ifc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-linux-ifc
subjects:
  - kind: ServiceAccount
    name: '{{ include "chaos-linux-ifc.serviceAccountName" . }}'