{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "chaos-linux-ifc.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "chaos-linux-ifc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
