apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-manager-config
  namespace: {{ .Release.Namespace | quote }}
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  REDIS_SSL_ENABLED: 'false'
  REDIS_CERT_PATH: '/opt/harness/svc/redis_labs_ca_truststore'
  REDIS_EVENTS_FWK_NAMESPACE: ''
  REDIS_CERT_PATH: '/opt/harness/svc/redis_labs_ca_truststore'
  REDIS_DATABASE: '0'
  REDIS_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_LOCK_ENDPOINT: 'redis://redis-sentinel-harness.{{ .Release.Namespace }}:6379'
  REDIS_LOCK_SSL_ENABLED: 'false'
  REDIS_LOCK_NAMESPACE: ''
  REDIS_LOCK_DATABASE: '0'
  PORTAL_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/chaos/kserver/api'
  SUBSCRIBER_IMAGE: {{ include "chaos-manager.subscriberImage" . }}
  CONTAINER_RUNTIME_EXECUTOR: 'k8sapi'
  ARGO_WORKFLOW_CONTROLLER_IMAGE: {{ include "chaos-manager.argoWorkflowControllerImage" . }}
  ARGO_WORKFLOW_EXECUTOR_IMAGE: {{ include "chaos-manager.argoWorkflowExecutorImage" . }}
  LITMUS_CHAOS_OPERATOR_IMAGE: {{ include "chaos-manager.litmusChaosOperatorImage" . }}
  LITMUS_CHAOS_RUNNER_IMAGE: {{ include "chaos-manager.litmusChaosRunnerImage" . }}
  LITMUS_CHAOS_EXPORTER_IMAGE: {{ include "chaos-manager.litmusChaosExporterImage" . }}
  CHAOS_MANAGER_VERSION: '0.8.0'
  INFRA_DEPLOYMENTS: '["app=chaos-exporter", "name=chaos-operator", "app=workflow-controller"]'
  ACCESS_CONTROL_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/authz/api'
  NG_MANAGER_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/ng/api'
  NG_MANAGER_SVC_ENDPOINT: 'http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090'
  PLATFORM_SERVICE_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/gateway/audit/api'
  ENTERPRISE_HUB_BRANCH_NAME: '{{ .Values.enterpriseHubBranchName }}'
  DEFAULT_CHAOS_EXPERIMENT_LIMIT: '{{ .Values.chaosExperimentLimit }}'
  DEFAULT_CHAOS_HUB_LIMIT: '{{ .Values.chaosHubLimit }}'
  DEFAULT_CHAOS_GAMEDAY_LIMIT: '{{ .Values.chaosGamedayLimit }}'
  DEFAULT_CHAOS_HUB_SIZE: '{{ .Values.chaosHubSize }}'
  DEFAULT_PARALLEL_CHAOS_EXPERIMENT_RUNS: '{{ .Values.parallelChaosExperimentRuns }}'
  SKIP_SECURE_VERIFY: '{{ .Values.skipSecureVerify }}'
  ENTERPRISE_HUB_SECRET: ""
  ENTERPRISE_HUB_TOKEN: ""
  K8S_IFS_VERSION: '0.8.0'
  K8S_INFRA_SERVER_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/chaos/kserver/api'
  LOG_WATCHER_IMAGE: {{ include "chaos-manager.logWatcherImage" . }}
  LOG_SERVICE_ENDPOINT: 'http://log-service.{{ .Release.Namespace }}.svc.cluster.local:8079'
  LINUX_INFRA_GQL_SERVER_ENDPOINT: "{{ .Values.global.loadbalancerURL }}/chaos/lserver/api"
  LINUX_INFRA_RPC_SERVER_ENDPOINT: "chaos-linux-ifs-service.{{ .Release.Namespace }}.svc.cluster.local:5000"
  LOG_WATCHER_IMAGE: {{ include "chaos-manager.logWatcherImage" . }}