apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-manager-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-manager.labels" . | nindent 4 }}
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  PLATFORM_SERVICE_ENDPOINT: 'http://platform-service:9005/api'
  ENTERPRISE_HUB_BRANCH_NAME: '{{ .Values.enterpriseHubBranchName }}'
  EXPERIMENT_HELPER_IMAGE_VERSION: '{{ .Values.expHelperImageVersion }}'
  SKIP_SECURE_VERIFY: '{{ .Values.skipSecureVerify }}'
  K8S_INFRA_SERVER_ENDPOINT: 'http://chaos-k8s-ifs-service:6000'
  LOG_WATCHER_IMAGE: {{ include "chaos-manager.logWatcherImage" . }}
  LINUX_INFRA_SERVER_ENDPOINT: '{{ .Values.global.loadbalancerURL }}/chaos/lserver/api'
  LINUX_INFRA_SERVER_SVC_ENDPOINT: 'http://chaos-linux-ifs-service:4000'
  DEFAULT_CHAOS_EXPERIMENT_LIMIT: '{{ .Values.chaosExperimentLimit }}'
  DEFAULT_CHAOS_HUB_LIMIT: '{{ .Values.chaosHubLimit }}'
  DEFAULT_CHAOS_GAMEDAY_LIMIT: '{{ .Values.chaosGamedayLimit }}'
  DEFAULT_CHAOS_HUB_SIZE: '{{ .Values.chaosHubSize }}'
  DEFAULT_PARALLEL_CHAOS_EXPERIMENT_RUNS: '{{ .Values.parallelChaosExperimentRuns }}'
  DEFAULT_CHAOS_EXPERIMENT_RUN_LIMIT: '100000'
  DEFAULT_GAME_DAY_RUNS_PER_GAME_DAY_LIMIT: '1000'
  DEFAULT_EXPERIMENTS_PER_GAME_DAY_RUN_LIMIT: '20'
  SRM_CHANGE_SOURCE_REDIS_STREAM: 'chaos_change_events'
  SAAS_ENABLED: 'false'
  APP_AI_ENDPOINT: ''
  LOG_INDIRECT_UPLOAD: 'false'
  LINUX_CHAOS_ENABLED: 'true'
  {{- if .Values.allowedOrigins }}
  ALLOWED_ORIGINS: '{{ .Values.allowedOrigins }}'
  {{- else }}
  ALLOWED_ORIGINS: "{{ .Values.global.loadbalancerURL }}"
  {{- end -}}

  {{- if .Values.global.imageRegistry }}
  DEFAULT_IMAGE_REGISTRY_SERVER: '{{ .Values.global.imageRegistry }}'
  {{- else }}
  DEFAULT_IMAGE_REGISTRY_SERVER: 'docker.io'
  {{- end -}}

  {{- if .Values.imageRegistryAccount }}
  DEFAULT_IMAGE_REGISTRY_ACCOUNT: '{{ .Values.imageRegistryAccount }}'
  {{- else }}
  DEFAULT_IMAGE_REGISTRY_ACCOUNT: 'chaosnative'
  {{- end -}}
