{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-manager-ingress-130
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: chaos-manager-service
                port:
                  number: {{ .Values.service.port }}
            path: /smp/chaos/manager/api(/|$)(.*)
            pathType: Prefix
          - path: /chaos/manager/api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chaos-manager-service
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.global.ingress.tls.enabled }}
    {{- range .Values.global.ingress.hosts }}
      host: {{ . | quote }}
    {{- end }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}
