apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chaos-manager-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: chaos-manager
