apiVersion: v1
data:
  CHAOS_SERVICE_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  NG_JWT_SECRET: SUMwNExZTUJmMWxEUDVvZVk0aHVweGQ0SEpoTG1ONmF6VWt1M3hFYmVFM1NVeDVHM1pZemhiaXdWdEs0aTdBbXF5VTlPWmt3QjR2OEU5cU0=
  REDIS_LOCK_PASSWORD: ""
  JWT_SECRET: ZE9rZHNWcWRSUFBSSkczMVhVMHFZNE1QcW1CQk1rMFBUQUdJS002TzdUR3Foanl4U2NJZEplODBtd2g1WWI1ekYzS3hZQkh3NkIzTGZ6bHE=
  REDIS_PASSWORD: ""
kind: Secret
metadata:
  name: chaos-manager-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-manager.labels" . | nindent 4 }}
type: Opaque

{{- if .Values.jobs.chaos_db_upgrade.enabled }}
---
apiVersion: v1
data:
  SLACK_URL: {{ .Values.jobs.chaos_db_upgrade.slackURLToNotify | b64enc | quote }}
kind: Secret
metadata:
  name: chaos-db-upgrade-job-secret
  namespace: {{ .Release.Namespace }}
type: Opaque

{{- end }}