{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "chaos-manager.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "chaos-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
