{{- if .Values.global.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-web-ingress-130
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-web.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: chaos-web-service
                port:
                  number: {{ $svcPort }}
            path: /smp/chaos(/|$)(.*)
            pathType: Prefix
          - path: /chaos(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chaos-web-service
                port:
                  number: {{ $svcPort }}
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}