apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chaos-web-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-web.labels" . | nindent 4 }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: chaos-web
